version: "3.7"

services:

  postgres:
    container_name: ORDER_API_POSTGRES
    image: postgres:latest
    hostname: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: super_admin
      POSTGRES_PASSWORD: super_password
      POSTGRES_DB: ORDERS_DB
    volumes:
      - SPRING_DB_API_VOLUME:/var/lib/postgresql/data
      - ./docker/postgres/shared/:/shared/
    restart: unless-stopped
    networks:
      - interapi
      - apidb

  springbootapp:
    build: .
    container_name: ORDER_API_SPRING
    environment:
      SPRING_PROFILES_ACTIVE: prod
    ports:
      - 8082:8080
    depends_on:
      - postgres
    links:
      - postgres
    networks:
      - apidb
      - interdb

  pgadmin:
    container_name: ORDER_API_PGADMIN
    image: dpage/pgadmin4
    ports:
      - "5555:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: superadmin@springapi.org
      PGADMIN_DEFAULT_PASSWORD: superpassword
      PGADMIN_SERVER_JSON_FILE: /pgadmin4/conf/server.json
    volumes:
      - ./docker/pgadmin/:/pgadmin4/conf/
    restart: unless-stopped

volumes:
  SPRING_DB_API_VOLUME:

networks:
  interapi:
    name: ordersapi_interapi
    driver: bridge
  apidb:
    name: ordersapi_apidb
    driver: bridge
  default:
    name: ordersapi_default
    driver: bridge
  interdb:
    name: ordersapi_interdb
    driver: bridge
